# Generated by Django 5.1.2 on 2024-10-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('coment', models.CharField(max_length=100)),
            ],
        ),
    ]
